# Generated by Django 4.2.6 on 2023-11-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='nationality',
            field=models.CharField(default='US', max_length=50),
        ),
    ]
