# Generated by Django 4.2.6 on 2023-11-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_details_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='sex',
            new_name='gender',
        ),
    ]
