# Generated by Django 4.2.6 on 2023-11-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loloutplays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loloutplaysstory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
