# Generated by Django 4.2.6 on 2023-11-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loloutplays', '0003_alter_loloutplaysstory_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loloutplaysstory',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
