# Generated by Django 4.2.6 on 2023-11-17 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loloutplays', '0004_alter_loloutplaysstory_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='loloutplaysstory',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
